cnn_model_options:
  mid_channels: 64
  out_channels: 64
  kernel_size: 10
  target_column: resistance_ratio
  sequence_length: 100
  step_size: 1
  batch_size: 32
  hidden_size: 32
  num_layers: 2
  num_classes: 1
  learning_rate: 0.0001
  num_epochs: 20
  group_label: exp_no
  feature_columns:
    - timestamp_bin
    - A1_Resistance